import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {uiClick,uiCheck} from './ui-controls.mjs';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = fileURLToPath(new URL('..',import.meta.url));
const out = path.resolve(process.env.TEST_OUTPUT_DIR || path.join(root,'test-output/presentation'));
fs.mkdirSync(out,{recursive:true});
const config = JSON.parse(fs.readFileSync(path.join(root,'vercel.json')));
const fixture = fs.readFileSync(path.join(root,'tests/fixtures/tts.json'));
let mode = 'normal';
const server = http.createServer(async(req,res)=> {
  for(const h of config.headers[0].headers) res.setHeader(h.key,h.value);
  if(req.url==='/api/tts') {
    for await(const _ of req) {}
    res.writeHead(mode==='error'?503:200,{'Content-Type':'application/json'});
    return res.end(mode==='error'?'{}':fixture);
  }
  const file = req.url==='/'?'index.html':decodeURIComponent(req.url.slice(1).split('?')[0]);
  const types = {'.html':'text/html','.mjs':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'};
  try {const data=fs.readFileSync(path.join(root,'public',file));res.writeHead(200,{'Content-Type':types[path.extname(file)]||'text/plain'});res.end(data);}
  catch {res.writeHead(404);res.end();}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage'],headless:true});
const context=await browser.newContext({viewport:{width:1365,height:850},acceptDownloads:true});
await context.route('**/firebase-adapter.mjs',route=>route.fulfill({contentType:'application/javascript',body:"export function createTransport(){return {list:async()=>{throw Error('Offline fixture')},watch:()=>()=>{}};}"}));
const page=await context.newPage(), errors=[], report=[];
page.on('pageerror',e=>errors.push(e.message));
page.setDefaultTimeout(10000);
const check=name=>report.push({name,status:'passed'});
const shot=async name=>{
  const fullPage=await page.locator('dialog[open]').count()===0;
  if(fullPage) await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  return page.screenshot({path:path.join(out,name),fullPage,animations:'disabled'});
};
const stage=async mode=>{await uiClick(page,`[data-mode="${mode}"]`);await page.waitForFunction(m=>document.querySelector('#mode-label').textContent===m,{listen:'Listen',dict:'Dictation',shadow:'Shadowing',review:'Review'}[mode]);};
try {
  await page.goto(url);
  await page.waitForSelector('#demo');
  await page.evaluate(()=>document.fonts.ready);
  assert(await page.evaluate(()=>document.fonts.check('400 13px Poppins') && document.fonts.check('600 20px Poppins')));
  check('Poppins loads locally with the production CSP');
  await shot('library-empty.png');
  await uiClick(page,'#demo');
  await page.waitForSelector('#workspace:not([hidden])');
  assert.equal(await page.locator('.sidebar').count(),0);
  const boxes=await page.evaluate(()=>['.player-panel','.exercise-panel'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,bottom:r.bottom};}));
  assert(boxes[1].y>=boxes[0].bottom-1 && Math.abs(boxes[0].x-boxes[1].x)<1);
  check('all learning stages share one centered vertical workspace');
  const ids=await page.evaluate(()=>[...document.querySelectorAll('[id]')].map(e=>e.id));
  assert.equal(ids.length,new Set(ids).size);
  check('controls and dialog labels have unique IDs');
  await stage('dict');
  assert(await page.locator('#caption').isHidden());
  await page.locator('#dict-answer').fill('Good morning!');
  await uiClick(page,'#check');
  assert.equal(await page.locator('#dict-result .result-score').innerText(),'100%');
  assert.equal(await page.locator('#progress-text').innerText(),'0/10 câu');
  await stage('shadow');
  assert(await page.locator('#spoken-text').isHidden());
  await page.locator('#speech-details > summary').click();
  await page.locator('#spoken-text').fill('Good morning!');
  await uiClick(page,'#compare-speech');
  assert.equal(await page.locator('#speech-result .result-score').innerText(),'100%');
  assert.equal(await page.locator('#progress-text').innerText(),'1/10 câu');
  check('progress reflects actual Dictation and Shadowing mastery, not the cursor');
  assert.equal(await page.locator('#speech-comparison').getAttribute('open'),null);
  assert(await page.locator('#speech-result .result-tokens').isHidden());
  assert(await page.locator('#shadow-result-actions #shadow-run').isVisible());
  assert.equal(await page.locator('#shadow-run').innerText(),'Luyện lại');
  assert(await page.locator('#shadow-next').isVisible());
  await page.locator('#speech-comparison > summary').click();
  assert(await page.locator('#speech-result .result-tokens').isVisible());
  assert.equal(await page.locator('#speech-result .correct').count(),2);
  await page.locator('#speech-comparison > summary').click();
  check('shadowing results open with a real score, collapsible word feedback, retry and next actions');
  await page.locator('#spoken-text').fill('Good');
  assert.equal(await page.locator('#speech-result').getAttribute('data-stale'),'true');
  assert(await page.locator('#transcript-note').isVisible());
  assert.equal(await page.locator('#speech-result .result-score').innerText(),'100%');
  await page.locator('#spoken-text').fill('Good morning!');
  assert.equal(await page.locator('#speech-result').getAttribute('data-stale'),'false');
  check('editing a transcript labels the previous result without silently recalculating it');
  await page.locator('#speech-details > summary').click();
  await shot('shadow-result-desktop.png');
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await shot('shadow-result-mobile.png');
  await page.setViewportSize({width:1365,height:850});
  await uiClick(page,'#next');
  assert((await page.locator('#caption').innerText()).includes('Could I have'));
  assert(await page.locator('#spoken-text').isHidden());
  await shot('shadowing-desktop.png');
  check('shadowing starts with concise actions; editable transcript stays accessible in a disclosure');
  assert(await page.locator('#new').evaluate(e=>e.classList.contains('outline')));
  assert(await page.evaluate(()=>getComputedStyle(document.querySelector('#main-play')).backgroundColor!==getComputedStyle(document.querySelector('#shadow-run')).backgroundColor));
  check('the current learning action has visual priority over create and idle playback controls');
  await page.locator('#mode-menu > summary').focus();
  await page.keyboard.press('ArrowDown');
  assert.equal(await page.locator('#mode-menu').getAttribute('open'),'');
  await shot('stage-menu.png');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#mode-menu').getAttribute('open'),null);
  assert(await page.locator('#mode-menu > summary').evaluate(e=>e===document.activeElement));
  check('stage menu supports keyboard opening, Escape and focus return');
  await page.locator('#display-menu > summary').click();
  await page.locator('#show-translation').check();
  assert(await page.locator('#translation').isVisible());
  await page.locator('#show-translation').uncheck();
  assert(await page.locator('#translation').isHidden());
  await page.locator('#mode-menu > summary').click();
  assert.equal(await page.locator('#display-menu').getAttribute('open'),null);
  await page.locator('#lesson-title').click();
  assert.equal(await page.locator('#mode-menu').getAttribute('open'),null);
  check('display options work, only one menu opens, and outside clicks dismiss it');
  await uiClick(page,'#main-play');
  await page.waitForFunction(()=>!document.querySelector('#model').paused);
  await page.waitForFunction(()=>document.querySelector('#main-play').getAttribute('aria-label')==='Tạm dừng');
  await uiClick(page,'#main-play');
  assert(await page.locator('#model').evaluate(e=>e.paused));
  assert.equal(await page.locator('#main-play').getAttribute('aria-label'),'Tiếp tục');
  const before=await page.locator('#model').evaluate(e=>e.currentTime);
  await uiClick(page,'#show-notes');
  assert(await page.locator('#model').evaluate(e=>e.paused));
  await page.locator('#notes').fill('Listen for the connected /v/ sound.');
  await page.locator('#lesson-notes').fill('A little practice, every day.');
  await shot('notes-drawer.png');
  await page.keyboard.press('Escape');
  await uiClick(page,'#main-play');
  await page.waitForFunction(()=>!document.querySelector('#model').paused);
  assert(await page.locator('#model').evaluate((e,t)=>e.currentTime>=t,before));
  await page.locator('#speed').selectOption('1.25');
  assert.equal(await page.locator('#model').evaluate(e=>e.playbackRate),1.25);
  await uiClick(page,'#show-settings');
  assert(await page.locator('#model').evaluate(e=>!e.paused));
  await shot('voice-drawer.png');
  await page.keyboard.press('Escape');
  await uiClick(page,'#stop');
  check('unified Play/Pause resumes the same audio; notes and voice panels preserve playback and drafts');
  await uiClick(page,'#show-progress');
  assert((await page.locator('#progress-overview').innerText()).includes('1/10'));
  await shot('progress-drawer.png');
  await uiClick(page,'[data-action="show-sentences"]');
  assert(await page.locator('#progress-dialog').isHidden());
  assert(await page.locator('#sentence-dialog').isVisible());
  assert.equal(await page.locator('#transcript-list [data-jump]').count(),10);
  await page.keyboard.press('Escape');
  const count=await page.locator('#sentence-numbers .sentence-number').count();
  assert.equal(count,10);
  assert.equal(await page.locator('.sentence-number.completed').count(),1);
  check('sentence buttons show real completion; list and statistics open without stacking panels');
  await stage('dict');
  await uiClick(page,'#show-sentences');
  assert(!(await page.locator('#transcript-list').innerText()).includes('Could I have'));
  await page.keyboard.press('Escape');
  await page.locator('#dict-answer').fill('Could I have a tea please?');
  await uiClick(page,'#check');
  assert(await page.locator('#dict-result .missing').count()>0);
  await uiClick(page,'#hint');
  await shot('dictation-desktop.png');
  check('dictation hides answers in captions and sentence list; feedback and hints remain inline');
  await page.locator('#dict-answer').fill('Could I have a cup of tea, please?');
  await page.locator('#dict-options > summary').click();
  await page.locator('#strict').check();
  await page.locator('#dict-options > summary').click();
  await uiClick(page,'#check');
  assert.equal(await page.locator('#dict-result .result-score').innerText(),'100%');
  check('strict grading remains reachable from its options menu');
  await stage('shadow');
  await uiClick(page,'#edit-sentence');
  await page.locator('#edit-translation').fill('Cho tôi một tách trà, được không?');
  await page.locator('#edit-form button[type="submit"]').click();
  await page.waitForSelector('#edit-dialog:not([open])',{state:'attached'});
  check('sentence menu edits and saves the original sentence fields');
  await uiClick(page,'#delete-lesson');
  assert(await page.locator('#confirm-dialog').isVisible());
  assert.equal(await page.locator('#confirm-cancel').evaluate(e=>e===document.activeElement),true);
  await shot('delete-dialog.png');
  await uiClick(page,'#confirm-cancel');
  assert.equal(await page.locator('#lesson-title').innerText(),'At the café');
  await uiClick(page,'#delete-lesson');
  await page.keyboard.press('Escape');
  assert(await page.locator('#workspace').isVisible());
  check('styled deletion confirmation cancels safely with a button or Escape');
  await uiClick(page,'#new');
  await page.locator('#new-title').fill('An unfinished lesson');
  await page.locator('#new-text').fill('Keep this text when closing is cancelled.');
  await page.keyboard.press('Escape');
  assert(await page.locator('#confirm-dialog').isVisible());
  await uiClick(page,'#confirm-cancel');
  assert.equal(await page.locator('#new-text').inputValue(),'Keep this text when closing is cancelled.');
  await page.keyboard.press('Escape');
  await uiClick(page,'#confirm-accept');
  await page.waitForSelector('#create-dialog:not([open])',{state:'attached'});
  assert(await page.locator('#create-dialog').isHidden());
  assert.equal(await page.locator('#lesson-title').innerText(),'At the café');
  check('dismissing an unfinished lesson confirms discard and cancellation keeps form input');
  await uiClick(page,'#edit-sentence');
  const translation=await page.locator('#edit-translation').inputValue();
  await page.locator('#edit-translation').fill('This edit has not been saved.');
  await uiClick(page,'[data-close="edit-dialog"]');
  assert(await page.locator('#confirm-dialog').isVisible());
  await uiClick(page,'#confirm-cancel');
  assert.equal(await page.locator('#edit-translation').inputValue(),'This edit has not been saved.');
  await page.keyboard.press('Escape');
  await uiClick(page,'#confirm-accept');
  await page.waitForSelector('#edit-dialog:not([open])',{state:'attached'});
  await uiClick(page,'#edit-sentence');
  assert.equal(await page.locator('#edit-translation').inputValue(),translation);
  await page.keyboard.press('Escape');
  check('close buttons and Escape protect unsaved sentence edits without modifying saved data');
  await stage('dict');
  await page.locator('#dict-answer').fill('');
  await uiClick(page,'#check');
  assert(await page.locator('#global-status').isVisible());
  const toast=await page.locator('#global-status').boundingBox();
  assert(toast.x>900 && toast.y>600 && toast.y+toast.height<=850);
  await shot('toast-desktop.png');
  await page.locator('#global-status .toast-close').click();
  assert(await page.locator('#global-status').isHidden());
  check('notifications appear in a corner and can be dismissed without moving the learning layout');
  await uiClick(page,'#export');
  await shot('export-dialog.png');
  const [file]=await Promise.all([page.waitForEvent('download'),page.locator('#export-confirm').click()]);
  await file.saveAs(path.join(out,'lesson.shadow.json'));
  const portable=JSON.parse(fs.readFileSync(path.join(out,'lesson.shadow.json')));
  assert.equal(portable.lesson.notes,'A little practice, every day.');
  assert.equal(Object.values(portable.lesson.progress).filter(p=>p.completed).length,1);
  check('file menu exports the existing format with notes and real progress');
  await stage('shadow');
  for(const width of [320,375,390,768,1365]) {
    await page.setViewportSize({width,height:width<600?844:768});
    await page.evaluate(()=>document.fonts.ready);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`);
    assert(await page.locator('#main-play').isVisible());
    assert(await page.locator('#shadow-run').isVisible());
    if (width===1365) {
      const footer=await page.locator('.sentence-strip').boundingBox();
      assert(footer.y+footer.height<=768,'laptop sentence navigation fits the viewport');
    }
  }
  await page.setViewportSize({width:390,height:844});
  await shot('shadowing-mobile.png');
  await stage('dict');
  await shot('dictation-mobile.png');
  await stage('review');
  await shot('review-mobile.png');
  await uiClick(page,'#export');
  await page.keyboard.press('Escape');
  check('all stages and menus remain reachable on 320–1365px screens without horizontal overflow');
  await page.setViewportSize({width:1365,height:850});
  await shot('review-desktop.png');
  await uiClick(page,'#sentence-numbers [data-jump="1"]');
  assert(await page.locator('#dict-pane').isVisible());
  await stage('review');
  check('review sentence navigation returns to the real dictation activity');
  await uiClick(page,'#change-lesson');
  await shot('library-desktop.png');
  assert(await page.locator('#empty').isVisible());
  await page.locator('#lesson-search').fill('café');
  assert.equal(await page.locator('[data-lesson]').count(),1);
  await page.locator('[data-lesson]').click();
  await uiClick(page,'#lesson-menu [data-action="show-notes"]');
  assert.equal(await page.locator('#lesson-notes').inputValue(),'A little practice, every day.');
  await page.keyboard.press('Escape');
  check('library navigation, search and return preserve saved lesson data');
  await page.locator('#lesson-file').setInputFiles(path.join(out,'lesson.shadow.json'));
  await page.waitForSelector('#confirm-dialog[open]');
  assert((await page.locator('#confirm-title').innerText()).includes('Thay dữ liệu'));
  await uiClick(page,'#confirm-accept');
  await page.waitForSelector('#confirm-dialog:not([open])',{state:'attached'});
  assert.equal(await page.locator('#lesson-title').innerText(),'At the café');
  check('styled import confirmation restores an existing lesson without changing the portable format');
  await uiClick(page,'#new');
  await page.locator('#new-title').fill('Long lesson with a very long title — a test of wrapping and navigation');
  await page.locator('#new-text').fill(Array.from({length:45},(_,i)=>`Alexandria: This is practice sentence number ${i+1}, with a little more content to check wrapping.`).join('\n'));
  await uiClick(page,'#analyse');
  await shot('create-dialog.png');
  await uiClick(page,'#create-confirm');
  await page.waitForFunction(()=>document.querySelector('#lesson-title').textContent.startsWith('Long lesson'));
  await page.setViewportSize({width:320,height:700});
  await page.waitForFunction(()=>document.querySelectorAll('#sentence-numbers .sentence-number').length===7);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.equal(await page.locator('#sentence-numbers .sentence-number').count(),7);
  await uiClick(page,'#show-sentences');
  await page.locator('#jump').selectOption('44');
  assert((await page.locator('#sentence-position').innerText()).includes('45 / 45'));
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#next-footer').isDisabled(),true);
  check('long titles and lessons wrap safely; drawer jump reaches the final sentence');
  await uiClick(page,'#delete-lesson');
  await uiClick(page,'#confirm-accept');
  await page.waitForSelector('#empty:not([hidden])');
  assert.equal(await page.locator('[data-lesson]').count(),1);
  check('accepting the styled confirmation deletes only the chosen lesson');
  await uiClick(page,'#tts-tab');
  await page.locator('#tts-title').fill('An audio to remember');
  await page.locator('#tts-text').fill('Good morning. Could I have a cup of tea, please?');
  await uiClick(page,'#tts-generate');
  await page.waitForSelector('#tts-output:not([hidden])');
  await page.setViewportSize({width:1365,height:850});
  await shot('converter-desktop.png');
  await page.setViewportSize({width:390,height:844});
  await shot('converter-mobile.png');
  await uiClick(page,'#tts-delete');
  assert((await page.locator('#confirm-title').innerText()).includes('MP3'));
  await uiClick(page,'#confirm-accept');
  await page.waitForFunction(()=>document.querySelector('#tts-count').textContent==='0 đoạn');
  assert(await page.locator('#tts-output').isHidden());
  check('MP3 history uses the same styled confirmation and keeps its conversion controls');
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(out,'presentation-ui-report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
} catch(e) {
  await shot('presentation-failure.png');
  console.error('PASSED',report,'PAGE_ERRORS',errors);
  throw e;
} finally {await context.close();await browser.close();server.close();}
